### ISSUE TITLE
Shortcuts `0`,`1`-`9` to set a class on a label do not work on azerty keyboard.

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#380]
**Describe the bug**
Shortcuts `1`-`9` to set a class on a label do not work on azerty keyboard. Instead the direct keys below the numbers (`&`, `é`, `"`, `'` ...) work.

**To Reproduce**
1. Create a class
2. Right click on a label
3. On an Azerty keyboard, press `shift` + `1` to set the label to class 1. I does not work.
4. Press `&` (on Mac), it works.

**Expected behavior**
Add to the keys under the numbers, the numbers themselves as shortcuts.

**Screenshots**
![IMG_5480](https://user-images.githubusercontent.com/16015322/130947846-a2034153-eaa4-4185-8c8f-7bd7f14f1a0a.JPG)

**Desktop (please complete the following information):**
 - OS: Mac 11.5.2
 - Browser Brave
 - Version 1.28.105

**Additional context**

**Comment by crubier** [comment]
I don't have an Azerty Keyboard. Can someone with an Azerty keyboard try to take this one ? 

In the key press code, we should check the code as we do today OR that the key is a number
