### ISSUE TITLE
An invalid query on GraphiQL closes the DB and makes the LabelFlow app to "lose" data

### ISSUE THREAD

**Issue by nicOwlas** [Labelflow/labelflow#384]
**Describe the bug**
An invalid query on GraphiQL closes the DB and makes the labelling interface to lose data

**To Reproduce**
1. Create a dataset on labelflow
2. Go to https://labelflow.ai/graphiql
3. Do a valid query like
```
query images {
  images(first:10){
    id
    name
  }
}
```
4. Now do an invalid query like
```
query images {
  exportToCoco(first:10){
    id
    name
  }
}
```
5. Go to https://labelflow.ai/local/datasets and refresh the page. The dataset has disappeared and you cannot create a new dataset

**Expected behavior**

**Screen recording**
https://user-images.githubusercontent.com/16015322/131139217-69a7b83c-5ffd-4095-b870-0cb0b3dbdfc9.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave

**Comment by etiennedupont** [comment]
Fixed with @crubier on #252, closing.
