### ISSUE TITLE
See blog post preview (image / description) in social medias

### ISSUE THREAD

**Issue by geoffreyvancassel** [labelflow/labelflow#470]
When publishing a blog article on social medias, I expect having the main blog images appearing with the URL like this one
![image](https://user-images.githubusercontent.com/18551789/135053703-2dcaab34-56b5-4461-8c8c-5cc055c32ac6.png)

but instead I have that

![image](https://user-images.githubusercontent.com/18551789/135053779-1c51b737-118b-458e-b872-df2b9559c9f5.png)

Ideally we can also see the blog description field into social media preview

**Tasks**
- [x] Display on social networks, blog article cover picture
- [x] Display the blog description field into social media preview (@geoffreyvancassel do you see the description on some social media and can you upload a screenshot?)

**Comment by geoffreyvancassel** [comment]
Facebook

![image](https://user-images.githubusercontent.com/18551789/135438484-bf8c6d02-556d-40ca-a45d-bade533c299f.png)

Twitter
![image](https://user-images.githubusercontent.com/18551789/135438591-ec2a8a9d-b505-4a3f-abf8-36a38363732b.png)

Linkedin 
![image](https://user-images.githubusercontent.com/18551789/135438652-c6f42798-32c4-4362-9856-f20b4fcb1ca8.png)

**Comment by LouisAllen7** [comment]
Re-opening this issue as the problematic behaviour has returned!

**Comment by nacho-carnicero** [comment]
Can you give more details? Is it happening on all social media?

**Comment by LouisAllen7** [comment]
Specific to Facebook. On other platforms, the post preview is the headline image from Stapi, however on Facebook it previews the default LabelFlow image
<img width="676" alt="Screenshot 2021-11-25 at 11 19 11" src="https://user-images.githubusercontent.com/57493990/143423598-e06fbfc4-ae5d-443d-bbbd-1dbd957667ec.png">

**Comment by LouisAllen7** [comment]
Same link previewed on Linkedin for your reference. 
<img width="509" alt="Screenshot 2021-11-25 at 11 21 23" src="https://user-images.githubusercontent.com/57493990/143423751-75cee556-3f71-4b10-b370-7b2f0ae16616.png">

**Comment by nacho-carnicero** [comment]
Ok thanks, I'll create a new issue specific for this, as it seems to be a different issue than this one

**Comment by nacho-carnicero** [comment]
Opened in #612
