### ISSUE TITLE
Backup Sterblue DB

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#492]
**Objective**
- Secure images and labels stored on the Sterblue platform so that we do not lose data when we switch off the Sterblue "products".
- Store the images in a way it is "easy" to access the images & labels of a user/organization
- Store in a way it is possible to transfer part of it to LabelFlow in the future.

## Export

- [x] Write query to export images and attached objects (organization => Workspace / Missions => Dataset)
- [x] 1 query for organization / members (clean manually, email not end with, action @nicOwlas @LouisAllen7  ) / missions
- [x] Deduplicate mission ids in JS (as several members of a same organization will have access to the same missions)
- [x] Write script with Sterblue SDK (prisma version) running locally
  - [ ] ~~Script converts the json extracted from the Sterblue DB to the LabelFlow json format (the json file list images and has an extra field `meta` to list structures, operators etc.)~~
  - [x] The script renames the images from `original.jpeg` to `imageName-imageId.jpeg`
  - [x] It creates 1 bucket per organization named `sterblueExport-organizationName-organizationId`
  - [x] It creates 1 folder file per mission named ~~`missionName-missionId`~~  `YYYY-MM-DD-missionName-missionId.jpeg`
  - [x] Store in the mission folder the LabelFlow json named `missionName-missionId.json`
  - [x] Store the mission images in the mission folder
  - [x] In `metadata.json` append to the file URL the suffix to directly access the file (generaly `/original.jpeg`)

## Export queries
Query for each mission:
```
query getMissionParameters {
  missions(where: {id: "xxx"}) {
    id
    name
    createdAt
    type
    plan {
      id
      parameters
    }
    execution {
      id
      images(where: {valid: true}) {
        id
        capturedAt
        cameraMake
        cameraModel
        cameraLensMake
        cameraIso
        cameraAperture
        cameraShutterSpeed
        cameraFieldOfViewHorizontal
        cameraFieldOfViewVertical
        width
        height
        location {
          latitude
          longitude
          altitude
          roll
          pitch
          yaw
        }
        file {
          name
          contentType
          url
        }
        structures {
          id
          name
          parameters
          location {
            latitude
            longitude
            altitude
          }
          model {
            type
          }
          parents {
            id
            name
            parameters
            location {
              latitude
              longitude
              altitude
            }
            model {
              type
            }
            parents {
              id
              name
              parameters
              location {
                latitude
                longitude
                altitude
              }
              model {
                type
              }
              parents {
                id
                name
                parameters
                location {
                  latitude
                  longitude
                  altitude
                }
                model {
                  type
                }
              }
            }
          }
        }
        detections {
          id
          createdAt
          geometry
          author {
            id
            name
          }
          comments {
            id
            author {
              id
              name
            }
            content
          }
          type {
            id
            name
          }
          level
          structure {
            id
            name
            model {
              type
            }
          }
          anomaly {
            id
            level
            location {
              latitude
              longitude
              altitude
            }
            comments {
              id
              author {
                id
                name
              }
              content
            }
            structure {
              id
              name
              model {
                type
              }
            }
          }
        }
      }
      trajectory
    }
  }
}
```

Query at the organization/bucket level (we still need to continue the DB cleaning and link an anomaly level mapping of every structure type to every organizations that will be exported)
```
query getOrganization {
  organizations(where: {id: "xxx"}) {
    id
    name
    anomalyLevelMappings {
      id
      description
      parameters
      structureType
      anomalyTypes {
        id
        name
        description
      }
    }
  }
}
```

**Comment by etiennedupont** [comment]
Same question as for https://github.com/labelflow/labelflow/issues/640: what about missions without organization, should we drop them?

**Comment by nicOwlas** [comment]
There is no direct link today between missions and organization. We are making sure with @LouisAllen7 that every users having relevant missions is linked to an organization, that way his/her missions will be imported. (more detailed comment in #640)

**Comment by etiennedupont** [comment]
> There is no direct link today between missions and organization.

Yes there is! But it's rarely set 

> his/her missions will be imported. 

Ok so we import missions on a per-user basis, not per organization. Do you know how to link a user to the mission he/she can access?

**Comment by nicOwlas** [comment]
I did not know! As far as I know the app and the platform was not creating this link when a user was creating a mission.

The user has any of the following role on the mission: operator/expert/client/inspector

**Comment by etiennedupont** [comment]
Just to clarify: should we include under an organization bucket all missions linked to any of the admins or only the missions that are common to every admin?
In the first proposition, we need to be careful about super users like the sterblue ones (but there might be others?)

**Comment by nicOwlas** [comment]
All missions linked to any admin. We have removed super users while doing the cleaning. Hopefully all. We'll double check that.

**Comment by nicOwlas** [comment]
I checked the content of metadata.json. Could you put the content of the query below? Could you also append `original.jpeg` to the file url so that it's the link to download the file? Are there any cases where it would not be original.jpeg the last part of the url?

We are missing the anomalyLevelMapping, a json at the bucket level with the answers to the a query listing the mappings will solve this issue.


Query for each mission:
```
query getMissionParameters {
  missions(where: {id: "xxx"}) {
    id
    name
    createdAt
    type
    plan {
      id
      parameters
      structurePlans {
        id
        structures {
          id
          name
          model {
            id
            type
            name
          }
          parents {
            id
            name
            model {
              id
              type
              name
            }
            parents {
              id
              name
              model {
                id
                type
                name
              }
            }
          }
        }
      }
    }
    execution {
      id
      images(where: {valid: true}) {
        id
        capturedAt
        cameraMake
        cameraModel
        cameraLensMake
        cameraIso
        cameraAperture
        cameraShutterSpeed
        cameraFieldOfViewHorizontal
        cameraFieldOfViewVertical
        width
        height
        location {
          latitude
          longitude
          altitude
        }
        file {
          name
          contentType
          url
        }
        structures {
          id
          name
          model {
            type
          }
        }
        detections(first: 10) {
          id
          createdAt
          geometry
          author {
            id
            name
          }
          comments {
            id
            author {
              id
              name
            }
            content
          }
          type {
            id
            name
          }
          level
          structure {
            id
            name
            model {
              type
            }
          }
          anomaly {
            id
            level
            location {
              latitude
              longitude
              altitude
            }
            comments {
              id
              author {
                id
                name
              }
              content
            }
            structure {
              id
              name
              model {
                type
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by nicOwlas** [comment]
I updated the export query and added it in the issue description directly (the issue description is the single source of truth). 

@LouisAllen7 @RaynalHugo could you double-check this [query](https://github.com/labelflow/labelflow/issues/492#issue-1016434581) if we are not missing anything important?
The goal is to have all the info needed to regenerate report if the customer want (images/detections/anomalies/comments + info on the structures inspected and the location&orientation of the drone while doing its inspections).

**Comment by etiennedupont** [comment]
@nicOwlas I see a lot of depth inside the images due to structures and their ancestors, which is not optimal because many images share the same structures and there will be a lot of duplicate information. Couldn't we simply add once for all the structure plans inside the mission (containing all that depth), and just query the structures id in the images?

**Comment by etiennedupont** [comment]
Actually same remark for anomalies, we could query them inside the mission execution rather than in every detection

**Comment by etiennedupont** [comment]
Done
