### ISSUE TITLE
Perform Stripe integration

### ISSUE THREAD

**Issue by nacho-carnicero** [labelflow/labelflow#524]
This is an issue that was created to discuss questions that arose from the tech time done with @RaynalHugo to integrate with Stripe.

 - What should be the successful redirection page when a user has made a payment on Stripe?
   - The workspace billing page? (Problem if the webhook notifying that the subscription was created arrives after the page reloads: the user won't see the updated plan)
   - A "Successful payment" page?

 - Should we create directly a subscription for Community users on Stripe, or only create a subscription when a user is paying?
   - We need to enter payment details for creating a subscription, so it would be better to only create it once the user wants to pay (to have the "no credit card needed" experience)
 
- Should we delete the Stripe subscription when a user downgrades his plan from a paying one to the Community one?

- Is it possible to create a Subscription without a payment method? (This way, we could create a subscription even for free plans) And then specify a payment method migrating to a paid plan.

Work to do: 
- [ ] Store a subscription per workspace and update this subscription when the user updates it.
- [ ] Properly update plans when the subscription status changes
- [ ] Deal with what happens when the user goes back to a less complete plan and is over the new images/annotations limit.
- [ ] properly name the API routes 
- [ ] Be able to visualize & update the billing method (credit card)

**Comment by RaynalHugo** [comment]
Closing in favour of #527
