### ISSUE TITLE
Update community plan to include an online workspace

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#528]
- [x] Edit website description of the community plan
- Do enforce any other limits for now
  - Do not limit number of workspace creation
  - Do not limit number of users / images etc.

### Plans

**Community**

- Smart labeling
- 1,000 hosted images
- Unlimited local images
- Unlimited datasets
- Dataset import/export
- Unlimited users

**Starter**

- Smart labeling
- 5,000 hosted images
- Unlimited local images
- Unlimited datasets
- Dataset import/export
- Unlimited users

**Pro**

- Smart labeling
- 50,000 hosted images
- Unlimited local images
- Unlimited datasets
- Dataset import/export
- Unlimited users

**Comment by RaynalHugo** [comment]
I am taking care of this in #541 as I am also changing the pro price from 199$ to 149$
