### ISSUE TITLE
Online workspaces bugs before release

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#572]
## Description
Online workspaces bugs and improvements before releasing. Tests were done on the workspace released branch.

## Must have (organized from highest to lowest priority)

- [x] I cannot create a workspace. When signed in and creating a workspace I still get the sign in modal after entering a name in the workspace creation modal. This query fails with error: `0: {message: "The column `Workspace.stripeCustomerId` does not exist in the current database.",…}` <img width="500" alt="Screenshot 2021-11-10 at 11 16 42" src="https://user-images.githubusercontent.com/16015322/141122819-7b60c00e-65dc-4525-8dc3-6e6a7e786201.png">

- [x] Edit: it now works ~~After creating of a workspace, I cannot create a dataset (error 400)~~ <img width="500" alt="Screenshot 2021-11-10 at 11 16 05" src="https://user-images.githubusercontent.com/16015322/141094790-62e90876-d7e9-4ed5-8510-4aea01715c20.png">
- [x] Members
  - [x] The list of members displays 0 members, though there should be the workspace creator at least <img width="500" alt="Screenshot 2021-11-10 at 11 16 42" src="https://user-images.githubusercontent.com/16015322/141094869-242214a6-f4bb-4eae-b905-6c521d253368.png">
  - [x] Invitation modal: emails are not being sent.
  - [x] Invitation modal: there are no alerts saying it failed or succeeded
- [x] Settings
  - [x] The settings page appear broken, no avatar nor workspace name is displayed <img width="500" alt="Screenshot 2021-11-10 at 11 12 59" src="https://user-images.githubusercontent.com/16015322/141094295-af6ac9bc-98bf-4d72-99fc-39414d47e15c.png">
- [x] Sign out
  - [x] When signing out from my online workspace, the automatic redirection to the local workspace does not work. I'm staying on the online workspace page but the workspace switcher is renamed to `Unnamed Workspace` <img width="1680" alt="Screenshot 2021-11-10 at 11 34 18" src="https://user-images.githubusercontent.com/16015322/141097671-2cace31d-f18a-4451-845c-c79cfd26e964.png">
- [x] Navigation between images on an online workspace redirects to the local workspace.

### Image upload

- [x] I cannot upload images. I get this error on the `createImageMutation`:
```
{"errors":[{"message":"Getting from Supabase storage, could not fetch image at url https://labelflow-d27kdajhi-labelflow.vercel.app/api/uploads/0e5a1310-c375-4d47-8eb3-714cd1531ccf/a7074b51-3a61-449b-8622-7e0afbeafbb4.jpeg properly, code 500","locations":[{"line":2,"column":3}],"path":["createImage"]}],"data":{"createImage":null}}
```
 <img width="500" alt="Screenshot 2021-11-10 at 16 22 53" src="https://user-images.githubusercontent.com/16015322/141141074-0018cc0f-0e2c-4e1e-bd71-46396ae470ec.png">

### Members invitation

- [x] After clicking on create a new workspace and signing in, the sign in email redirects to the workspace creation modal though the workspace has been created. It would be better to be redirected to the newly created workspace page.

- [x] invitation modal: the email addresses cannot be written on the same line or it displays an error. The example though shows email addresses on the same line <img width="500" alt="Screenshot 2021-11-10 at 11 12 59" src="https://user-images.githubusercontent.com/16015322/141094509-bc61072a-6fa4-4d8e-838f-b9c485d458f3.png">

**Comment by RaynalHugo** [comment]
Image upload was failing due to missing env vars in VERCEL

**Comment by RaynalHugo** [comment]
> After clicking on create a new workspace and signing in, the sign in email redirects to the workspace creation modal though the workspace has been created. It would be better to be redirected to the newly created workspace page.

I can't reproduce this case. However, one enhancement I could see would be to store the name of the workspace to create in the URL. This way when the user get the sign in link, the modal would be pre-filled with the input they previously put.
