### ISSUE TITLE
Say something if user tries to login by email without filling email

### ISSUE THREAD

**Issue by crubier** [labelflow/labelflow#575]
When the users clicks "login with email without filling the form (email adress), it should warn them beforehand, not say "mail sent"

<img width="1176" alt="Screenshot 2021-11-12 at 17 08 20" src="https://user-images.githubusercontent.com/2954572/141506593-bbea82c6-f7d6-4828-90b8-fda3fb6b7e5f.png">

**Comment by RaynalHugo** [comment]
Done in #581
