### ISSUE TITLE
Export does not work on online workspaces

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#578]
**Describe the bug**
Export does not work on online workspaces

**To Reproduce**
- [x] Export to COCO with or without images does not work. query `exportDatasetUrl` fails with error: 
```
errors: [{message: "btoa is not defined", locations: [{line: 2, column: 3}], path: ["exportDataset"]}]
```

- [x] Export to YOLO with or without images does not work. query `exportDatasetUrl` fails with error: 
```
{"errors":[{"message":"blob is not supported by this platform","locations":[{"line":2,"column":3}],"path":["exportDataset"]}],"data":null}
```

**Comment by etiennedupont** [comment]
Fixed in #592
