### ISSUE TITLE
Auto polygon improvements

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#594]
**Describe the bug**
Tested on: https://labelflow-git-feature-508-iog-workflows-labelflow.vercel.app/local/datasets

**To Reproduce**

- [x] Rename the tool to `Auto Polygon` instead of `Auto Polygon Tool`
- [x] Make the donut grey darker: [mockup](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3271%3A31271) (grey-700 with a pass through of 70% on Figma)
- [x] Remove the segmented control buttons (polygon/auto polygon) when in creation mode
https://user-images.githubusercontent.com/16015322/142401711-54636a00-71c4-445f-a068-19c3db35a063.mov
- [x] Do not display a border on the inside hole of the donut: [mockup](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3271%3A31271)
- [x] The first remove point cannot be deleted
- [x] Undo is buggy, should have the same behaviour as Polygon.
- [x] IOG doesn't work on online workspaces
- [x] Investigate if canvas is resized before inference

**Comment by etiennedupont** [comment]
>  Do not display a border on the inside hole of the donut: mockup

Are you sure? This makes the resizing of the canvas harder to discover

**Comment by etiennedupont** [comment]
Done in #624
