### ISSUE TITLE
Small potential improvements on LabelFlow hosted version

### ISSUE THREAD

**Issue by geoffreyvancassel** [labelflow/labelflow#596]
- [x] I would change the text by: This workspace is private and images are stored locally on your device. To collaborate online and invite people, switch to an online workspace ![image](https://user-images.githubusercontent.com/18551789/142435627-410e6a02-f1e6-4c74-b6f4-ce22830f9790.png)
- [x] Remove the soon ![image](https://user-images.githubusercontent.com/18551789/142436239-9c815e65-f781-428c-a2a3-fd6cd8a0e665.png)
- [ ] ~~When clicking on the magic link I come back on the website but not in the workspace, clicking on the link "try it now" brings in the workspace session correctly though~~ (will be fixed in prod)
- [ ] ~~Maybe more on the onboarding video side but  this is not spontaneous to find the "create workspace" part~~ (will be done in a seperate issue) ![image](https://user-images.githubusercontent.com/18551789/142437138-41c2e2c7-9f11-4a91-a774-b689bffe539d.png)
- [x] When overlayed the "new member" button is not visible anymore ![image](https://user-images.githubusercontent.com/18551789/142437369-1dbba8ff-9337-4d38-9d2e-7dfac91f639a.png)
- [x] "Adding members to the workspace will give them access to every dataset in the workspace". To be changed by "Adding members will give them access to every dataset in the workspace" ![image](https://user-images.githubusercontent.com/18551789/142437698-9b85cf1a-510a-4213-84cd-9ae515992788.png)
- [x] @geoffreyvancassel  could you detail this point? When trying to invite myself I got this error message when clicking in the magic link sent (it was ok in the magic link as a workspace owner though) ![image](https://user-images.githubusercontent.com/18551789/142438224-4b137b47-d0d0-4f02-a567-22de8ca97bf1.png)
- [x] action @nicOwlas : I would remind in 3 bullet points what I have access to in this community plan + my usage and associated limits in order I understand when I will have to upgrade. I would also put a link (to open in a new page) toward the pricing section https://labelflow.ai/website#pricing ![image](https://user-images.githubusercontent.com/18551789/142438491-2c474e2a-af0f-423b-8755-8be96a578cac.png)
- [x] teamed up instead of partners ![image](https://user-images.githubusercontent.com/18551789/142438894-32466d1d-3e44-42c9-a68a-efacdf178028.png)
- [x] Action @nicOwlas: Edit, better to leave the platform for this one to avoid thinking we are being scammed by having another window opening for the payment. ~~check behaviour: In order not to quit the platform, the stripe page should open in a new window~~

**Comment by Jordanlelay** [comment]
solved by #674
