### ISSUE TITLE
Create 1 connection to the DB per upload instead of per file

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#603]
**Context**
- When doing an upload, there is 1 connection to the DB per file uploaded which saturates PGBouncer

**Objective**
- Robustify how many uploads can happen in parallel without saturating PGBouncer

**Solution 1**
- [ ] Call `getUploadTarget` 1 time per file
  - [ ] If `getUploadTarget` calls the DB, then code and call a new resolver getUploadTargets that returns many upload URLs
  - [ ] If no keep as is
- [ ] Code and call a new resolver `createManyImages` with all the urls returned by `getUploadTarget` (thumbnails are created in the `createImage` mutation). Upload directly to AWS thanks to the presigned URL returned by AWS through the grapql resolvers (hosted on Vercel)
- [ ] Eventually batch getUploadTarget if not enough

Blocked by #607 
Blocked by #626

**Comment by RaynalHugo** [comment]
Blocked by #626 
I can't upload images on the distant workspace, making this hard to test

**Comment by RaynalHugo** [comment]
Done in #603
