### ISSUE TITLE
Auto polygon does not execute on the workspace feature branch: `Body exceeded 1mb limit`

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#609]
## Describe the bug
Auto polygon does not execute on workspace feature branch: `Body exceeded 1mb limit`

## To Reproduce
- Create an auto polygon on this image: https://labelflow-r4sy51gqz-labelflow.vercel.app/2021-11-22-2-drab/datasets/test/images/1ca39d9f-9a7d-4c8c-823c-f0ede92ab4fc?selected-tool=iog
- Error
Query
```
mutation runIog($id: ID!, $imageUrl: String, $x: Float, $y: Float, $width: Float, $height: Float, $pointsInside: [[Float!]], $pointsOutside: [[Float!]], $centerPoint: [Float!]) {
  runIog(
    data: {id: $id, imageUrl: $imageUrl, x: $x, y: $y, width: $width, height: $height, pointsInside: $pointsInside, pointsOutside: $pointsOutside, centerPoint: $centerPoint}
  ) {
    id
    type
    geometry {
      type
      coordinates
      __typename
    }
    x
    y
    width
    height
    smartToolInput
    labelClass {
      id
      color
      __typename
    }
    __typename
  }
}
```

Response:
```
Body exceeded 1mb limit
```

![image](https://user-images.githubusercontent.com/16015322/143260930-1c2a752c-76b5-4b5d-a333-96d116c94d76.png)

## Solution
- [ ] Give iog an admin role on the bucket storing the iog images
- [ ] Local side
  - [ ] Upload with a pre-signed url to bypass the 5MB limitation in a bucket (store every image at the root). Add a rule to remove the image automatically after 1 day.
  - [ ] iog should take the url from the image on the S3 bucket
  - [ ] Edit to be done in another issue: ~~Possibility to put the image in the iog cache directly with minio~~
- [ ] Server side
  - [ ] Directly use the image S3 url
  - [ ] Modify iog to accept urls on top of data url

**Comment by etiennedupont** [comment]
Fixed in #622
