### ISSUE TITLE
Display a loading state on the dataset page

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#627]
## Tasks
- Implement a spinner in place of the 1st dataset card to display datasets are loading ([chakra component here](https://chakra-ui.com/docs/feedback/spinner))

## Mockup

![image](https://user-images.githubusercontent.com/16015322/145822801-4c22f34e-2552-4dc8-9b79-a9839ad42d0c.png)

```
<Spinner
  thickness='4px'
  speed='0.65s'
  emptyColor='gray.200'
  color='#31CECA'
  size='xl'
/>
```

![image](https://user-images.githubusercontent.com/16015322/145822752-aee43c43-25ee-47c1-9845-b5b176051627.png)

**Comment by 2Clutch** [comment]
Hello. Found your project on `goodfirstissues.com`, and I'd like to take on this task if no one else is working on it.

**Comment by nicOwlas** [comment]
@2Clutch it's yours! Thanks a lot! I updated the description to have a skeleton instead of a spinner.
Once you start working on it, could you assign yourself move it in the `In progress` column in the [project board here](https://github.com/labelflow/labelflow/projects/1)?

 Let us know if you have any questions.

**Comment by 2Clutch** [comment]
Thank you @nicOwlas. I sincerely appreciate it.

If I understand properly, the workflow should be:
1. User click on `Create a new Project`
2. User selects an image to upload
3. Display `skeleton` as upload is being processed.
4. Display image once upload has been processed successfully.

Am I accurate, in my description of what I believe is needed to address this issue?

**Comment by nicOwlas** [comment]
@2Clutch the workflow is much simpler for this issue:
1. The user opens the dataset gallery url (today: https://labelflow.ai/local/datasets)
2. The dataset cards are being loaded and in the meantime, we display to the user the dataset card skeleton
3. Once the actual dataset card is loaded we replace the skeleton with its dataset card

Today, as there is no skeleton, if the user's connection is slow, he/she would otherwise only see the `Create a new dataset` card and nothing else. He/she may think his/her datasets were lost where in fact they are being loaded in the background. Displaying the dataset card skeleton allows showing to the user that some elements on the page are being loaded.

You can open a PR and commit regularly so that we give you feedbacks along the way. When do you think you'll have time to start the issue?

**Comment by 2Clutch** [comment]
I'll get started over the weekend. I cloned the project and started going through the initial setup.

**Comment by 2Clutch** [comment]
Okay so I was able to clone and set up the project locally, which as far as I could tell based on the documentation involved just installing the various dependencies and running, `yarn start:web`. 

Could you please confirm that I don't need to set up a DB or anything? Not sure if it would be necessary for this task or not, but I would like to at least confirm that it's something I'll never have to do. That information could come in handy when trying to debug stuff.

**Comment by 2Clutch** [comment]
A couple of questions @nicOwlas.

1. I'm guess my work should be in `src/web/datasets`. Am I expect to edit one of the current components on build a new one?

2. Do I need to rebuild the project at every change for them to be reflected? I've made some tweaks trying to identify which component is behind `Create a new dataset` but none of my changes are being reflected despited relaunching the app a couple of times. I mean, I'm pretty sure `new-data-card.tsx` is the right file, but I figured this was an issue worth pointing it.

**Comment by RaynalHugo** [comment]
Hi @2Clutch, 

After discussing this a bit with the team, we realised that the solution proposed in the mockups doesn't really make sense. 

The mockup describes a state that doesn't exist at this point in the app. We query the list of all datasets and the related information in the same query. So, either we don't have data at all, or we have an array of datasets with all the data we need to display it. We never have a state where we know the user has N datasets, but we can't display them entirely and therefore should use skeleton components.

knowing this, we said that we would simply display a spinner next to the "create new project" card when the query is loading. This will let the user know that a query is pending, while still letting them create new projects if needed.

We will update the mockups accordingly.

**Comment by nicOwlas** [comment]
Mockups updated.

**Comment by RaynalHugo** [comment]
Apart from that, to answer your technical questions:

-  You don't need to start a database locally. The version you use when you run `yarn dev:web` uses a Service Worker and an IndexedDB to store images and data directly on your browser. So, no need to start anything apart from the web server.

- Yes, your work should mostly be on `typescript/web/src/components/datasets` and on `typescript/web/src/pages/[workspaceSlug]/datasets/index.tsx`. The first folder corresponds to the definition of all components. The second one is where data is fetch and where they are instantiated. I think you can simply edit the existing components, but feel free to add others if that makes sense.

- You should use the command `yarn dev:web` to have the hot reload. It starts a local development server. The command `yarn start:web` is used to start a local server with a production build generated by `yarn build:web`

If you have any additional questions, please, feel free to ask. 
We'd like to make it easier for external contributors to work on this project, so any feedback will be welcomed and useful for us to draft a `CONTRIBUTING.md` file

**Comment by Jordanlelay** [comment]
Resolved by #668

**Comment by 2Clutch** [comment]
Thank you so much for the prompt response. I think I have more clarity now. I'll go ahead and get started, and follow up with questions if something comes up.

**Comment by nicOwlas** [comment]
@2Clutch indeed, as this issue was quite high on the backlog and we were not sure when you would have time to go ahead on it, someone from the team took it.

Have a look at other `good first issues` in the [project](https://github.com/Labelflow/labelflow/projects/1) if you will. If you find one that appeals to you and has the tag `eng-ready` then do not hesitate to take it. Else if it has the tag `grooming needed`, you can start a conversation in the comments so that we take some time to better define the issue.

**Comment by 2Clutch** [comment]
How do I differentiate a ticket that's high on the backlog versus something that's not?

For better or worse, I am only willing to spend some of my spare time being a contributor so turn-around will not always be quick, especially early on as I familiarize myself with the code base. Assuming this is one of the main things you're looking for in a contributor, then maybe I'm not a good fit for this project.

Alternatively, maybe you should create a label that defines how high of a priority an issue is? I do not want to fall into a cycle where the issues I pick up are taken away with no warning because I'm not completing them quickly enough.

**Comment by nicOwlas** [comment]
You can visualize the priority order directly on [the project page](https://github.com/Labelflow/labelflow/projects/1), the issues at the top of the backlog column have the highest priority. When someone takes an issue, he moves it to the `In progress` column so that the issue is not picked twice.

![image](https://user-images.githubusercontent.com/16015322/146941620-a9cd5b8d-ec1f-4391-85a9-3b655e5999cc.png)

We are really happy to have external contributors and I sincerely apologize for the time you may have had already spent on this issue.

I'll add some more `good first issue` tags to increase the choice and make sure it's not urgently needed in the product so that you have time to complete it. For now [there is this one](https://github.com/labelflow/labelflow/issues/639) that comes to my mind.
