### ISSUE TITLE
Make the freehand drawing tool more accessible via a dedicated mode

### ISSUE THREAD

**Issue by bbenoist** [labelflow/labelflow#639]
**Is your feature request related to a problem? Please describe.**

As of now, the freehand mode is somewhat hidden in the polygon tool (press shift when drawing).

**Describe the solution you'd like (import visuals when possible)**

Add a new **Freehand** tool.

Icon could be the BoxIcon `pencil`:
![image](https://user-images.githubusercontent.com/2091902/145001110-df3d93de-ed76-4130-af94-3229e85c6a61.png)

**Describe alternatives you've considered**

None

**Additional context**

Canny request: https://labelflow.canny.io/admin/feedback/feature-requests/p/add-free-hand-drawing-tool?boards=feature-requests

**Comment by nicOwlas** [comment]
Poker planning: 1 day
