### ISSUE TITLE
Several classes can have the same color

### ISSUE THREAD

**Issue by Jordanlelay** [labelflow/labelflow#666]
**Describe the bug**
When creating a new label class, it is possible to generate several times the same label color since we can reorder them

**To Reproduce**
1. Go to the labeling tool and create a class, you will have to classes: Horse and the one you just generated
1. Go the classes page, Horse class should be first
1. Reorder the 2 classes and put Horse at last
1. Go back to the labeling tool and create an other class
1. The error is that the 2 classes generated have the same color

**Expected behavior**
Each class you generate (until you reach the limit of the hardcoded classes color) should have a unique color

**Screenshots**
![Capture d’écran 2021-12-17 à 11 25 27](https://user-images.githubusercontent.com/43350109/146530232-4df15a3a-42b7-434c-be2b-6cfea26be194.png)

**Desktop (please complete the following information):**
All versions affected

**Smartphone (please complete the following information):**
All versions affected

**Comment by Jordanlelay** [comment]
We could potentially ignore this bug if we let the users select the color themselves. Currently they cannot change the color once the class created

**Comment by nicOwlas** [comment]
Good catch. We can also fix the logic how the colour is assigned to a class. There is a list of predefined colours and we should avoid picking an already assigned colour.

**Comment by vincent-lecrubier-skydio** [comment]
😈

**Comment by Jordanlelay** [comment]
Closed by #673
