### ISSUE TITLE
Incorrect redirection when receiving an invitation to a workspace

### ISSUE THREAD

**Issue by Jordanlelay** [labelflow/labelflow#690]
**Describe the bug**
When receiving an invitation to join an online workspace, if the receiver is not logged in, a modal will appear for him to sign in. After entering the email address, the modal closes and a page not found error appears.

**To Reproduce**
- Invite someone to your online workspace and make him click the link he will receive by mail.
- The receiver of the invitation must not have used the platform at all.
- He will then be required to sign in by the app.
- After entering his mail for receiving the magic link, the sign in modal will close trying to redirect him to the first page of the tutorial, which does not exists because the user has not used the platform yet.
- A `Page not found` is rendered.

**Expected behavior**
The new user should not be redirected to the first page of the tutorial if he didn't intend to.
The new user should not see a `Page not found` among its first interactions with the platform.

**Comment by nicOwlas** [comment]
I could not reproduce @Jordanlelay. On my side, I'm redirected to the workspace I have just accepted the invitation from.

**Comment by nicOwlas** [comment]
Edit: I could reproduce if the cookie `hasUserTriedApp` does not exist. Then we have the welcome modal and the redirection to the local workspace.

**Comment by Jordanlelay** [comment]
It looks like the modal does not close anymore after entering the mail for signin so the `Page not found` error does not appear anymore
