### ISSUE TITLE
Labelling interface is very slow when there are multiple label classes

### ISSUE THREAD

**Issue by nacho-carnicero** [labelflow/labelflow#694]
**Describe the bug**
The labelling interface gets very slow when there are multiple label classes. The open layers part is fine, but all the business logic gets very slow (selecting a label to change it, select a new drawing tool etc...). 

We should virtualize the list of label classes in both menus (the context menu and the upper left menu).

**To Reproduce**
1. Create a new workspace + dataset
2. Upload an image
3. Create 400 label classes in the dataset
4. Create a label in the image
5. Try to use the labelling interface to create new labels with different tools, see how slow it gets

**Expected behavior**
The interface should not get slower as label classes increase

**Comment by etiennedupont** [comment]
Fixed in #695
