### ISSUE TITLE
405 error when trying to perform an auto polygon on the tutorial image (local workspace)

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#711]
## Describe the bug

405 error when trying to perform an auto polygon on the tutorial image (local workspace)

## To Reproduce

1.  Go to the [tutorial image number 3](https://labelflow.ai/local/datasets/tutorial-dataset/images/04f999da-780c-461c-8e8e-c3189ae560fb?selected-tool=iog)
2.  Add an Auto Polygon
3.  See 405 error

## Expected behavior
Normal Auto Polygon

## Screenshots
![image](https://user-images.githubusercontent.com/16015322/147732119-80d13f03-d4b2-4dde-9c93-5f7a64bac31e.png)

## Device information

 

- **Device:** 
- **OS:** 
- **Browser:** 
- **Version:**

**Comment by bbenoist** [comment]
Fixed by authorizing the correct environment variable to the Vercel environment
