### ISSUE TITLE
Error initiating!

### ISSUE THREAD

**Issue by nunoedgarhubsoftphotoflow** [labelflow/labelflow#754]
## To Reproduce

1. 
2. 
3. 
4. 

## Device information

 

- **Device:** 
- **OS:** 
- **Browser:** 
- **Version:**

**Comment by nicOwlas** [comment]
Hi @nunoedgarhubsoftphotoflow!
Could you tell us more about the browser you are using (incognito mode or normal) and what error you faced?

**Comment by nicOwlas** [comment]
Closing as we cannot reproduce.
