### ISSUE TITLE
Add image url to COCO or YOLO export files to allow exporting large datasets

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#781]
- [ ] For COCO: Add our own custom field such as image_url with a signed image URL valid for 7 days
- [ ] For YOLO: if images are not download, investigate if the `train.txt` file can have the images url instead of the relative paths to the files.

**Comment by valerian** [comment]
Generating S3 signed URLs of our images to make temporary URLs to export is technically not an issue, and we can set a TTL of our choice (to be discussed).

However our current architecture way of storing images will require to implement it in a way that is not the cleanest in my opinion (parsing the images URL from the database to extract the S3 keys).

Regarding the [COCO annotation data format](https://cocodataset.org/#format-data), we have two choices:
- Use the `coco_url` field, which proper usage is not explained in the official specifications, and that some people already use for scripts that "stream" COCO datasets.
- Add our own custom field such as `labelflow_url`, which is what [v7labs](https://darwin-py-sdk.v7labs.com/_modules/darwin/exporter/formats/coco.html) does, but this requires users to write/edit some script to support our custom field.

Regarding YOLO, there doesn't seem to be anything existing yet, but we could keep the file structure without the images, and add a file that just contains the list of images, one per line (to be investigated and discussed further).
