### ISSUE TITLE
Color gradient on user icon does not show up anymore. It's always white or empty

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#798]
## Bug

Color gradient on user icon does not show up anymore. It's always white. Bug is observed on Brave and Firefox with Google login and Magic link login.

### Brave
![image](https://user-images.githubusercontent.com/16015322/149742414-8428e192-7f95-4348-8916-28361ce1f221.png)

### Firefox
![image](https://user-images.githubusercontent.com/16015322/149742530-5e725ee2-63fc-4fc3-9a7f-fece2e1d1101.png)

**Comment by Jordanlelay** [comment]
looks ok for me, is it a new account that you've created ?

![Capture d’écran 2022-01-17 à 11 18 48](https://user-images.githubusercontent.com/43350109/149751553-62352d1d-4293-40a8-9b2c-8f2f2f720a84.png)

**Comment by nicOwlas** [comment]
> looks ok for me, is it a new account that you've created ?
> 
Ok good to know. Strange. It's my Sterblue account, so not new. I tried cleaning the cache, local storage, re-start SW etc. Always white on white. In dark mode it works though:
![image](https://user-images.githubusercontent.com/16015322/149754144-96f333a9-6d6a-4c67-bd65-28fa0d88f894.png)
![image](https://user-images.githubusercontent.com/16015322/149754356-5f84fbbe-e025-40c7-a487-2dab760e22f6.png)

**Comment by Jordanlelay** [comment]
Ok I see the problem, it comes from password less sign in

**Comment by nicOwlas** [comment]
With social sign-in (Google), only the gradient is missing for me:
![image](https://user-images.githubusercontent.com/16015322/149754846-de4c699f-4bc7-4313-9554-2344b6505e45.png)

**Comment by Jordanlelay** [comment]
There is no gradient when you use Google sign in, it should load an image from your Google account

**Comment by nicOwlas** [comment]
> There is no gradient when you use Google sign in, it should load an image from your Google account

I had a gradient before, I imagine it's a fallback if there is no image.
