### ISSUE TITLE
Detail the upload process (batching, thumbnail generation, upload etc.)

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#808]
> **TODO** Add whiteboard picture

**Comment by valerian** [comment]
![Image Upload Process drawio (1)](https://user-images.githubusercontent.com/239688/151035201-cce9fa8f-b71d-413d-830f-f521cab69d89.png)

When the user puts several images in the upload modal, the client will start uploading several of them in parallel, using X batches of N images. The current settings are 20 batches of 2 images each.

This diagram explains the upload of *one batch* of images:
- The client requests a new signed upload URL (and a future download URL as well) for each image individually (in parallel), which goes through our server (lambda), and queries the S3 bucket as well.
- The client uploads each image to its upload URL (in parallel).
- The client makes a single query with the information of all the images in the batch to our server (lambda).
  - It downloads all of the images from the S3 bucket.
  - It generates 5 thumbnails for each image, then uploads all of them to the S3 bucket.
  - It insert new database entries for each new images
  - It returns to the client the updated images informations, including database IDs and thumbnails URLS.

**Comment by nicOwlas** [comment]
> The current settings are 20 batches of 2 images each.
Typo I believe: 2 batches of 2 images each.

**Comment by valerian** [comment]
> > The current settings are 20 batches of 2 images each.
> 
> Typo I believe: 2 batches of 2 images each.

Not a typo, we used to have 2 batches of 10 images, we changed it to 20 batches of 2 images recently to fix the timing-out/slow uploads
