### ISSUE TITLE
Error when trying to import a COCO annotation file

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#860]
I have following error when trying to import this V7 generated COCO annotation file to LabelFlow:

The COCO import never ends, the import appears as locked. If I open the dataset in another tab the import succeeded though.
- [Annotation File](https://github.com/labelflow/labelflow/files/8018599/lonzee-2022-02-05.zip)
- [Dataset to perform debug tests](https://labelflow.ai/labelflow/datasets/bug-import-coco)

![image](https://user-images.githubusercontent.com/16015322/152867616-ba47f1bd-b223-40c1-8480-686ad3445341.png)

**Comment by nicOwlas** [comment]
@valerian : Link to the dataset on [drive](https://drive.google.com/drive/folders/15Dol-upAWz4IjtsBcv-r5zp1Q0UlUcL0?usp=sharing)

**Comment by nicOwlas** [comment]
For now I would say ignore them silently and we'll add in the documentation that we only support polygons ie `iscrowd:0`

**Comment by nicOwlas** [comment]
This could be the clear message. Could you add it?
2 tasks:

- [ ] Add a message with the number of ignored annotations if there are any.
- [ ] Change the icon for json files

![image](https://user-images.githubusercontent.com/16015322/153439009-de77dd3b-44b3-4494-95c3-a79f65d15304.png)

**Comment by valerian** [comment]
> This could be the clear message. Could you add it?
> 2 tasks:

Ok, I will do that
