### ISSUE TITLE
Invalid user sessions improperly handled on the delete service worker branch

### ISSUE THREAD

**Issue by valerian** [labelflow/labelflow#883]
## Describe the bug

**On drop service worker branch:**

When opening the website with an invalid user session (such as the session of a user that doesn't exist anymore), we are left on a completely blank page (nothing, no headers, no UI to log in/out)

This issue is possibly also present in other situations related to user sessions and rights.

## To Reproduce

1. Have a working logged in user session
2. Delete user from database, or use a fresh new test database
3. Go to any page of the website

## Expected behavior

User session should be deleted to allow signing in/up

## Additional information

The query that fails is `UserWithWorkspacesQuery`.
The error that I got was `{"errors":[{"message":"Couldn't find an user with id: \"8747d5b2-8861-4ff7-bf43-7e12bcd56860\"","locations":[{"line":2,"column":3}],"path":["user"]}],"data":null}`

**Comment by nicOwlas** [comment]
Good catch. Not critical for the release as a user cannot be deleted from the UI at this point.
