### ISSUE TITLE
GraphiQL displays an error on the delete service worker branch

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#884]
## Context

When writing a query, problem with the first character not being a `q`

![image](https://user-images.githubusercontent.com/16015322/154040337-4026885c-3da0-4377-83d5-3b88a6c56881.png)

**Comment by bbenoist** [comment]
Works locally: ![image](https://user-images.githubusercontent.com/2091902/154168867-ebddc4aa-1888-4114-a313-aae828277789.png)

**Comment by bbenoist** [comment]
Cannot reproduce on the preview deployment too:
![image](https://user-images.githubusercontent.com/2091902/154169227-bee6099c-0815-4f06-b6b2-2f28f115af86.png)
