### ISSUE TITLE
Fix CSV export

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#906]
- [x] White icons
- [x] Add tests
- [x] Remove option to add URLs (always have it in the CSV)
- [x] ~~Set the validity period to: 30 days~~

**Comment by valerian** [comment]
@nicOwlas what to display when we don't have options? 🤔
![Screenshot 2022-02-21 at 16 20 35](https://user-images.githubusercontent.com/239688/154983607-c61627e0-0933-43b2-b7b8-ce206cc5c53c.png)

**Comment by nicOwlas** [comment]
Can you skip the option modal and directly launch the download of the CSV?

**Comment by valerian** [comment]
AWS can't create signed URLs that expire in more than 7 days:
https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/

**Comment by nicOwlas** [comment]
@valerian we should be putting the `labelId` in the first column instead of the `imageId` no?
