### ISSUE TITLE
Featured articles are not visible anymore on labelflow.ai

### ISSUE THREAD

**Issue by Jordanlelay** [labelflow/labelflow#914]
## To Reproduce

1. Go to [labelflow homepage](https://labelflow.ai/)
2. Scroll down

## Expected behavior

The featured articles should be visible

## Solution
Do not return an empty table on labelflow.ai
`typescript/web/src/pages/index.tsx`

## Screenshots

<img width="1677" alt="Capture d’écran 2022-02-23 à 08 46 30" src="https://user-images.githubusercontent.com/43350109/155279331-fdd9c089-94e8-4219-9c87-edafcd658267.png">

## Device information

Every version affected

**Comment by nicOwlas** [comment]
Fixed apparently

**Comment by Jordanlelay** [comment]
No it's still on the [root page](https://labelflow.ai/)
It works on [website page](https://labelflow.ai/website) though, I think it's the one you were looking at
