### ISSUE TITLE
Docs are outdated

### ISSUE THREAD

**Issue by Jordanlelay** [labelflow/labelflow#920]
Our docs still mention service worker specific features
<img width="815" alt="Capture d’écran 2022-02-24 à 16 46 51" src="https://user-images.githubusercontent.com/43350109/155558409-4b1a2eb2-c315-4c70-9e63-17a8677d80b1.png">

**Comment by nicOwlas** [comment]
Oups. Thanks for the heads up. I'll update it.

**Comment by nicOwlas** [comment]
Updated on GitBook
